<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="sapra-ThinkPad-Edge-E430" ignored="0" name="Default test" tests="5" failures="1" timestamp="04 Jul 2017 18:38:34 GMT" time="0.418" errors="0">
  <testcase name="whenCreateMock_thenCreated" time="0.185" classname="com.javaSampleCode.mockito.MockitoSpySampleCode"/>
  <testcase name="whenCreateSpy_thenCreate" time="0.096" classname="com.javaSampleCode.mockito.MockitoSpySampleCode"/>
  <testcase name="whenSpyingOnList_thenCorrect" time="0.002" classname="com.javaSampleCode.mockito.MockitoSpySampleCode"/>
  <testcase name="whenStubASpy_thenStubbed" time="0.006" classname="com.javaSampleCode.mockito.MockitoSpySampleCode"/>
  <testcase name="whenUsingTheSpyAnnotation_thenObjectIsSpied" time="0.071" classname="com.javaSampleCode.mockito.MockitoSpySampleCode">
    <failure type="org.mockito.exceptions.misusing.NotAMockException" message="
Argument passed to verify() is of type ArrayList and is not a mock!
Make sure you place the parenthesis correctly!
See the examples of correct verifications:
    verify(mock).someMethod();
    verify(mock, times(10)).someMethod();
    verify(mock, atLeastOnce()).someMethod();">
      <![CDATA[org.mockito.exceptions.misusing.NotAMockException: 
Argument passed to verify() is of type ArrayList and is not a mock!
Make sure you place the parenthesis correctly!
See the examples of correct verifications:
    verify(mock).someMethod();
    verify(mock, times(10)).someMethod();
    verify(mock, atLeastOnce()).someMethod();
	at com.javaSampleCode.mockito.MockitoSpySampleCode.whenUsingTheSpyAnnotation_thenObjectIsSpied(MockitoSpySampleCode.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- whenUsingTheSpyAnnotation_thenObjectIsSpied -->
</testsuite> <!-- Default test -->
